spring:
  application:
    name: hhplus-lecture
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

